extends SceneTree

func _initialize() -> void:
	call_deferred("_run")

func frame(data: Dictionary) -> PackedByteArray:
	return ("data: " + JSON.stringify(data) + "\r\n\r\n").to_utf8_buffer()

func _run() -> void:
	var stream := CoreProgressStream.new()
	stream.configure(0, 90, 0, 4194304)
	stream.feed(frame({"prompt_progress": {"processed": 64, "total": 200}, "choices": []}), 80000)
	assert(stream.timeout_reason(95000).is_empty())
	stream.feed(frame({"prompt_progress": {"processed": 64, "total": 999}, "choices": []}), 160000)
	stream.feed(": ping\n\n".to_utf8_buffer(), 169000)
	assert(stream.timeout_reason(170000) == "no_progress")
	var zero := CoreProgressStream.new()
	zero.configure(0, 1, 0, 10000)
	zero.feed(frame({"prompt_progress": {"processed": 0}, "choices": []}), 900)
	assert(zero.timeout_reason(1000) == "no_progress")
	var total := CoreProgressStream.new()
	total.configure(0, 90, 120, 4194304)
	total.feed(frame({"prompt_progress": {"processed": 128}, "choices": []}), 119000)
	assert(total.timeout_reason(120000) == "total_budget")
	var chunks := CoreProgressStream.new()
	chunks.configure(0, 90, 0, 4194304)
	var utf := frame({"choices": [{"index": 0, "delta": {"content": "Привет 🌍"}, "finish_reason": null}]})
	for byte in utf: chunks.feed(PackedByteArray([byte]), 100)
	assert(chunks.content == "Привет 🌍")
	assert(not chunks.done)
	chunks.feed(frame({"choices": [{"delta": {}, "finish_reason": "stop"}]}), 101)
	chunks.feed("data: [DONE]\n\n".to_utf8_buffer(), 102)
	assert(chunks.done and chunks.error.is_empty())
	assert(chunks.result().choices[0].message.content == "Привет 🌍")
	var unfinished := CoreProgressStream.new()
	unfinished.feed("data: [DONE]\n\n".to_utf8_buffer(), 10)
	assert(not unfinished.error.is_empty())
	var malformed := CoreProgressStream.new()
	malformed.feed("data: {broken}\n\n".to_utf8_buffer(), 10)
	assert(not malformed.error.is_empty())
	var bounded := CoreProgressStream.new()
	bounded.configure(0, 1, 0, 3)
	bounded.feed(utf, 10)
	assert(not bounded.error.is_empty() and bounded.content.is_empty())
	var unbounded := CoreProgressStream.new()
	unbounded.configure(0, 0, 0, 0)
	assert(unbounded.timeout_reason(100000000).is_empty())
	var path := "user://core_wait_test.cfg"
	assert(CoreWaitPolicy.save({"stall_timeout_seconds": 1234.0, "total_timeout_seconds": 0.0, "response_max_bytes": 8000000}, path) == OK)
	# Simulate a new process: remove in-memory overrides and read persisted file.
	for key in CoreWaitPolicy.DEFAULTS: ProjectSettings.set_setting("aurorafox/core/" + str(key), null)
	assert(CoreWaitPolicy.limits(path).stall_timeout_seconds == 1234.0)
	assert(CoreWaitPolicy.limits(path).total_timeout_seconds == 0.0)
	assert(CoreWaitPolicy.save({"stall_timeout_seconds": -1}, path) == ERR_INVALID_PARAMETER)
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	print("AURORA_CORE_PROGRESS_STREAM_OK")
	quit(0)
