class_name OwnerResourcePolicy
extends RefCounted

const PATH := "user://owner_resources.cfg"
const DEFAULTS := {
	"sandbox_command_items": 64,
	"sandbox_cwd_chars": 1024,
	"sandbox_write_path_chars": 1024,
	"workspace_task_chars": 4000,
	"sandbox_exec_max_seconds": 300,
	"computer_http_max_seconds": 320,
	"computer_default_http_seconds": 8,
	"tool_computer_default_http_seconds": 12,
	"sandbox_default_http_seconds": 180,
	"computer_response_bytes": 0,
	"computer_http_error_chars": 2048,
	"computer_output_chars": 120000,
	"computer_capture_bytes": 8388608,
	"computer_uia_items": 250,
	"computer_uia_windows": 30,
	"computer_uia_controls": 40,
	"computer_uia_name_chars": 512,
	"computer_uia_type_chars": 64,
	"computer_uia_id_chars": 256,
	"computer_worker_seconds": 8,
	"computer_action_results": 512,
	"computer_action_identities": 0,
	"computer_action_text_chars": 20000,
	"computer_action_keys": 12,
	"computer_action_clicks": 3,
	"computer_action_scroll": 100,
	"computer_action_seconds": 5,
	"computer_action_worker_seconds": 10,

	"sandbox_write_bytes": 2000000,
	"sandbox_snapshot_entries": 5000,
	"sandbox_snapshot_bytes": 536870912,
	"research_request_seconds": 20,
	"research_collection_seconds": 45,
	"research_backoff_base_seconds": 300,
	"research_backoff_max_seconds": 21600,
	"research_backoff_failure_cap": 8,
	"research_error_chars": 240,
	"research_http_error_chars": 500,
	"research_stage_chars": 64,
	"research_endpoint_chars": 200,

	"research_response_bytes": 2097152,
	"research_log_bytes": 8388608,
	"research_summary_chars": 1800,
	"research_title_chars": 300,
	"research_error_items": 16,
	"speech_chunk_chars": 220,
	"speech_natural_min_chars": 96,
	"speech_sentence_min_chars": 18,

	"sandbox_read_bytes": 5000000,
	"sandbox_read_chars": 300000,
	"sandbox_tree_items": 1000,
	"sandbox_workspace_items": 30,
	"sandbox_event_items": 300,

	"project_index_source_bytes": 4194304,
	"project_index_file_symbols": 500,
	"project_index_search_results": 100,
	"project_index_symbol_results": 200,
	"project_index_query_chars": 2000,
	"project_index_symbol_query_chars": 500,
	"project_index_excerpt_chars": 1800,
	"project_index_result_symbols": 80,
	"project_index_health_http_seconds": 5,
	"project_index_build_http_seconds": 900,
	"project_index_search_http_seconds": 60,
	"project_index_manage_http_seconds": 30,

	"android_xls_file_bytes": 33554432,
	"android_xls_directory_entries": 4096,
	"android_xls_directory_depth": 64,
	"android_xls_shared_strings": 50000,
	"android_xls_sheets": 256,
	"voice_log_bytes": 5242880,
	"voice_log_chars": 1200,
	"knowledge_folder_files": 750,
	"knowledge_failure_items": 4,
	"improvement_ui_detail_chars": 2500,
	"improvement_ui_detail_items": 30,
	"improvement_ui_history_items": 100,
	"coordinator_event_items": 500,
	"coordinator_report_items": 20,
	"coordinator_detail_chars": 5000,
	"coordinator_detail_items": 50,
	"coordinator_index_files": 30000,
	"learning_promotion_history_items": 50,
	"learning_outcome_chars": 120,

	"candidate_project_files": 30000,
	"candidate_project_bytes": 2147483648,
	"candidate_source_bytes": 1048576,
	"candidate_proposal_attempt_multiplier": 3,
	"candidate_benchmark_seconds": 150,
	"candidate_history_items": 30,
	"candidate_review_source_chars": 120000,
	"candidate_reason_chars": 2000,
	"candidate_verification_chars": 1500,
	"candidate_saved_reason_chars": 4000,
	"candidate_saved_verification_chars": 3000,
	"candidate_history_text_chars": 1000,
	"candidate_evidence_items": 24,
	"hot_generated_bytes": 524288,
	"hot_project_files": 30000,
	"hot_project_bytes": 2147483648,
	"hot_diversity_items": 12,
	"hot_signature_reason_chars": 220,
	"hot_generation_error_items": 20,
	"hot_reason_chars": 1200,
	"hot_verification_chars": 800,
	"hot_review_source_chars": 7000,
	"hot_judge_reason_chars": 800,
	"hot_evidence_chars": 6000,
	"hot_evidence_items": 50,

	"learning_title_chars": 500,
	"learning_summary_chars": 3600,
	"learning_url_chars": 1000,
	"learning_context_data_chars": 4965,

	"core_fallback_items": 4,
	"core_error_chars": 600,
	"core_http_error_chars": 3000,
	"voice_segment_ms": 15000,

	"evolution_pending_ttl_seconds": 86400,
	"json_error_chars": 120,
	"evolution_recent_items": 64,
	"evolution_phase_items": 24,
	"evolution_generation_attempts": 24,
	"evolution_pending_items": 5,

	"knowledge_zip_entries": 5000,
	"knowledge_xml_member_bytes": 33554432,
	"knowledge_rich_chars": 4194304,
	"knowledge_epub_items": 256,
	"knowledge_epub_bytes": 33554432,
	"json_depth": 256,
	"json_scalar_bytes": 16777216,
	"json_records": 5000000,
	"json_aggregate_fields": 64,
	"json_aggregate_chars": 262144,

	"attachment_text_bytes": 2097152,
	"skill_json_bytes": 8388608,
	"skill_import_items": 2000,
	"skill_step_items": 64,
	"skill_tool_items": 32,
	"skill_name_chars": 120,
	"skill_summary_chars": 4000,
	"skill_goal_chars": 600,
	"skill_step_chars": 1200,

	"chat_attachment_chars": 6000,
	"chat_auto_title_chars": 38,
	"chat_title_chars": 60,
	"verification_trace_chars": 30000,
	"reflection_skills_chars": 30000,
	"reflection_failures_chars": 20000,
	"reflection_idea_items": 200,
	"agent_skill_items": 5,
	"agent_failure_items": 5,
	"reflection_failure_items": 20,
	"agent_retrieval_items": 10,
	"chat_retrieval_items": 2,
	"agent_recent_items": 8,
	"memory_recent_items": 12,
	"memory_retrieval_items": 8,
	"knowledge_chunk_chars": 1800,
	"knowledge_stream_batch_chars": 131072,
	"knowledge_write_batch_items": 2048,
	"knowledge_search_items": 6,
	"voice_tts_input_chars": 16000,
	"voice_cache_bytes": 536870912,
	"voice_mic_queue_chunks": 128,
	"voice_path_chars": 4096,
	"voice_stft_n_fft": 1024,
	"voice_stft_hop_length": 256,

	"work_error_chars": 2048,
	"work_summary_chars": 4096,
	"work_action_chars": 256,
	"learning_seen_items": 5000,
	"learning_claim_items": 5000,
	"learning_gap_items": 500,
	"learning_audit_items": 2000,

	"agent_max_steps": 18,
	"experience_failure_items": 300,
	"experience_checkpoint_items": 500,
	"experience_result_chars": 4000,
	"code_input_chars": 120000,
	"code_repair_chars": 60000,
	"code_rejected_chars": 30000,
	"code_files_chars": 90000,
	"code_repair_files_chars": 50000,
	"code_consult_files_chars": 120000,

	"chat_max_tokens": 768,
	"terse_max_tokens": 128,
	"memory_max_items": 5000,
	"knowledge_max_items": 10000,
	"dedupe_window": 1000,
	"index_batch": 64,
	"index_text_chars": 24000,
	"vector_tokens": 768,
	"vector_features": 4096,
	"task_trace_chars": 12000,
	"feedback_prompt_chars": 12000,
	"feedback_answer_chars": 20000,
	"feedback_summary_chars": 1200,
	"feedback_observed_chars": 2400,
	"feedback_lesson_chars": 2400,
	"direct_memory_chars": 240,
	"direct_history_items": 4,
	"direct_history_chars": 800,
	"agent_history_items": 24,
	"agent_history_chars": 16000,
	"attachment_items": 6,
	"attachment_excerpt_chars": 6000,
	"attachment_metadata_chars": 1800,
	"context_message_chars": 24000,
	"tool_result_chars": 5000,
	"tool_result_items": 25,
}
const LABELS := {
	"sandbox_command_items": "Песочница: аргументов команды (0 = все; перезапуск Computer)",
	"sandbox_cwd_chars": "Песочница: символов cwd (0 = все; перезапуск Computer)",
	"sandbox_write_path_chars": "Песочница: символов пути записи (0 = все; перезапуск Computer)",
	"workspace_task_chars": "Workspace: символов задачи (0 = все; перезапуск Computer)",
	"sandbox_exec_max_seconds": "Windows: потолок секунд команды (0 = без потолка)",
	"computer_http_max_seconds": "Computer: потолок секунд HTTP (0 = без потолка)",
	"computer_default_http_seconds": "ComputerClient: секунд HTTP по умолчанию (0 = только общий потолок)",
	"tool_computer_default_http_seconds": "Computer tools: секунд HTTP по умолчанию (0 = только общий потолок)",
	"sandbox_default_http_seconds": "Песочница Windows: секунд HTTP по умолчанию (0 = только общий потолок)",
	"computer_response_bytes": "Computer: байтов ответа HTTP (0 = все)",
	"computer_capture_bytes": "Computer: байтов stdout и stderr команды (0 = все)",
	"computer_uia_items": "Computer: элементов UIA (0 = без ограничения)",
	"computer_uia_windows": "Computer: окон UIA (0 = без ограничения)",
	"computer_uia_controls": "Computer: контролов на окно UIA (0 = без ограничения)",
	"computer_uia_name_chars": "Computer: символов имени UIA (0 = без ограничения)",
	"computer_uia_type_chars": "Computer: символов типа UIA (0 = без ограничения)",
	"computer_uia_id_chars": "Computer: символов ID UIA (0 = без ограничения)",
	"computer_worker_seconds": "Computer: секунд чтения экрана/UIA (0 = без ограничения)",
	"computer_action_results": "Computer: сохранённых результатов действий (0 = все; ID не забываются)",
	"computer_action_identities": "Computer: ёмкость ID действий (0 = без ограничения; при заполнении новые действия отклоняются)",
	"computer_action_text_chars": "Computer: символов ввода (0 = без ограничения)",
	"computer_action_keys": "Computer: клавиш в действии (0 = без ограничения)",
	"computer_action_clicks": "Computer: кликов в действии (0 = без ограничения)",
	"computer_action_scroll": "Computer: единиц прокрутки (0 = без ограничения)",
	"computer_action_seconds": "Computer: секунд ожидания/движения (0 = без ограничения)",
	"computer_action_worker_seconds": "Computer: секунд выполнения действия (0 = без ограничения)",
	"computer_output_chars": "Computer: символов вывода команды (0 = все)",
	"computer_http_error_chars": "Computer: символов ошибки HTTP (0 = все)",

	"sandbox_write_bytes": "Windows: байтов записи в песочницу (0 = все)",
	"sandbox_snapshot_entries": "Windows: записей снимка песочницы (0 = все)",
	"sandbox_snapshot_bytes": "Windows: байтов снимка песочницы (0 = все)",
	"research_request_seconds": "Research: секунд запроса (0 = без срока)",
	"research_collection_seconds": "Research: секунд сбора (0 = без срока)",
	"research_backoff_base_seconds": "Research: секунд начальной задержки после ошибки (0 = без задержки)",
	"research_backoff_max_seconds": "Research: максимум секунд задержки (0 = без лимита)",
	"research_backoff_failure_cap": "Research: предел счётчика ошибок для задержки (0 = без лимита)",
	"research_error_chars": "Research: символов ошибки в журнале (0 = все)",
	"research_http_error_chars": "Research: символов ошибки HTTP (0 = все)",
	"research_stage_chars": "Research: символов этапа диагностики (0 = все)",
	"research_endpoint_chars": "Research: символов адреса сервера (0 = все)",

	"research_response_bytes": "Research: байтов ответа (0 = без лимита)",
	"research_log_bytes": "Research: байтов журнала до ротации (0 = без лимита)",
	"research_summary_chars": "Research: символов резюме (0 = все)",
	"research_title_chars": "Research: символов заголовка (0 = все)",
	"research_error_items": "Research: ошибок в отчёте (0 = все)",
	"speech_chunk_chars": "Голос: символов сегмента TTS (0 = без лимита)",
	"speech_natural_min_chars": "Голос: минимум символов до естественного разделения",
	"speech_sentence_min_chars": "Голос: минимум символов предложения",

	"sandbox_read_bytes": "Песочница: байтов чтения (0 = без лимита)",
	"sandbox_read_chars": "Песочница: символов чтения (0 = все)",
	"sandbox_tree_items": "Песочница: элементов дерева (0 = все)",
	"sandbox_workspace_items": "Песочница: рабочих сред в списке (0 = все)",
	"sandbox_event_items": "Песочница: событий истории (0 = все)",

	"project_index_source_bytes": "Индекс проекта: байт одного исходника",
	"project_index_file_symbols": "Индекс проекта: символов на файл",
	"project_index_search_results": "Индекс проекта: предел результатов поиска",
	"project_index_symbol_results": "Индекс проекта: предел результатов поиска символов",
	"project_index_query_chars": "Индекс проекта: символов запроса",
	"project_index_symbol_query_chars": "Индекс проекта: символов запроса символов",
	"project_index_excerpt_chars": "Индекс проекта: символов отрывка",
	"project_index_result_symbols": "Индекс проекта: символов в результате",
	"project_index_health_http_seconds": "Индекс проекта: ожидание статуса, секунд (0 = без таймаута)",
	"project_index_build_http_seconds": "Индекс проекта: ожидание индексации, секунд (0 = без таймаута)",
	"project_index_search_http_seconds": "Индекс проекта: ожидание поиска, секунд (0 = без таймаута)",
	"project_index_manage_http_seconds": "Индекс проекта: ожидание состояния/очистки, секунд (0 = без таймаута)",

	"android_xls_file_bytes": "Android XLS: байт входного файла и потока",
	"android_xls_directory_entries": "Android XLS: записей OLE-каталога",
	"android_xls_directory_depth": "Android XLS: глубина OLE-каталога",
	"android_xls_shared_strings": "Android XLS: уникальных строк SST",
	"android_xls_sheets": "Android XLS: листов и метаданных листов",
	"voice_log_bytes": "Голос: байтов журнала до ротации (0 = без лимита)",
	"voice_log_chars": "Голос: символов диагностического сообщения",
	"knowledge_folder_files": "Knowledge: файлов из папки (0 = без лимита)",
	"knowledge_failure_items": "Knowledge: ошибок в итоге импорта (0 = все)",
	"improvement_ui_detail_chars": "Улучшения: символов отображаемых деталей",
	"improvement_ui_detail_items": "Улучшения: элементов отображаемых деталей",
	"improvement_ui_history_items": "Улучшения: записей истории",
	"candidate_project_files": "Core: файлов в копии проекта (0 = без лимита)",
	"candidate_project_bytes": "Core: байтов в копии проекта (0 = без лимита)",
	"coordinator_event_items": "Автономия: сохраняемых событий",
	"coordinator_report_items": "Автономия: событий в отчёте",
	"coordinator_detail_chars": "Автономия: символов деталей",
	"coordinator_detail_items": "Автономия: элементов деталей",
	"coordinator_index_files": "Автономия: файлов индекса проекта",
	"learning_promotion_history_items": "Обучение: истории продвижения утверждения",
	"learning_outcome_chars": "Обучение: символов итога попытки",

	"candidate_source_bytes": "Core кандидат: байтов исходного кода",
	"candidate_proposal_attempt_multiplier": "Core candidate: множитель попыток предложения",
	"candidate_benchmark_seconds": "Core candidate: секунд на benchmark-команду",
	"candidate_history_items": "Core кандидат: записей истории",
	"candidate_review_source_chars": "Core кандидат: символов исходника для оценки",
	"candidate_reason_chars": "Core кандидат: символов причины в проверке",
	"candidate_verification_chars": "Core кандидат: символов запрошенной проверки",
	"candidate_saved_reason_chars": "Core кандидат: сохраняемых символов причины",
	"candidate_saved_verification_chars": "Core кандидат: сохраняемых символов проверки",
	"candidate_history_text_chars": "Core кандидат: символов цели и ошибки в истории",
	"candidate_evidence_items": "Core кандидат: элементов результата в контексте",
	"hot_generated_bytes": "Hot extension: байтов сгенерированного модуля",
	"hot_project_files": "Hot extension: файлов импорта проекта",
	"hot_project_bytes": "Hot extension: байтов импорта проекта",
	"hot_diversity_items": "Hot extension: предыдущих вариантов в контексте",
	"hot_signature_reason_chars": "Hot extension: символов причины в сигнатуре",
	"hot_generation_error_items": "Hot extension: ошибок генерации в отчёте",
	"hot_reason_chars": "Hot extension: символов причины",
	"hot_verification_chars": "Hot extension: символов запрошенной проверки",
	"hot_review_source_chars": "Hot extension: символов исходника для оценки",
	"hot_judge_reason_chars": "Hot extension: символов причины оценки",
	"hot_evidence_chars": "Hot extension: символов результата в контексте",
	"hot_evidence_items": "Hot extension: элементов результата в контексте",

	"learning_title_chars": "Исследования: символов заголовка в Knowledge",
	"learning_summary_chars": "Исследования: символов данных в Knowledge",
	"learning_url_chars": "Исследования: символов URL в тексте",
	"learning_context_data_chars": "Исследования: символов текста без метки недоверенного источника",

	"core_fallback_items": "Core: локальных моделей за восстановление",
	"core_error_chars": "Core: символов ошибки модели",
	"core_http_error_chars": "Core: символов ошибки HTTP",
	"voice_segment_ms": "Android микрофон: длина сегмента, мс",

	"evolution_pending_ttl_seconds": "Evolution: срок ожидающего результата, секунд",
	"json_error_chars": "JSON: символов значения в диагностике",
	"evolution_recent_items": "Evolution: экспериментов в истории",
	"evolution_phase_items": "Evolution: фаз в истории эксперимента",
	"evolution_generation_attempts": "Evolution: попыток получить мутации",
	"evolution_pending_items": "Evolution: ожидающих результатов",

	"knowledge_zip_entries": "Knowledge ZIP-документы: записей каталога",
	"knowledge_xml_member_bytes": "Knowledge DOCX/ODT: байтов XML",
	"knowledge_rich_chars": "Knowledge: символов встроенного чтения документа",
	"knowledge_epub_items": "Knowledge EPUB: разделов",
	"knowledge_epub_bytes": "Knowledge EPUB: распакованных байтов",
	"json_depth": "JSON: глубина вложенности",
	"json_scalar_bytes": "JSON: байтов одного значения",
	"json_records": "JSON: потоковых записей",
	"json_aggregate_fields": "JSON: полей агрегированной записи",
	"json_aggregate_chars": "JSON: символов агрегированной записи",

	"attachment_text_bytes": "Вложения: байтов прямого чтения текста",
	"skill_json_bytes": "Импорт навыков: байтов JSON",
	"skill_import_items": "Импорт навыков: записей за импорт",
	"skill_step_items": "Импорт навыков: шагов",
	"skill_tool_items": "Импорт навыков: инструментов",
	"skill_name_chars": "Импорт навыков: символов имени",
	"skill_summary_chars": "Импорт навыков: символов описания",
	"skill_goal_chars": "Импорт навыков: символов цели",
	"skill_step_chars": "Импорт навыков: символов шага",

	"chat_attachment_chars": "Чат: сохраняемых символов вложения",
	"chat_auto_title_chars": "Чат: символов автоматического названия",
	"chat_title_chars": "Чат: символов заданного названия",
	"verification_trace_chars": "Проверка ответа: символов журнала",
	"reflection_skills_chars": "Самоанализ: символов навыков",
	"reflection_failures_chars": "Самоанализ: символов ошибок",
	"reflection_idea_items": "Самоанализ: сохранённых идей",
	"agent_skill_items": "Агент: навыков в контексте",
	"agent_failure_items": "Агент: ошибок в контексте",
	"reflection_failure_items": "Самоанализ: ошибок в контексте",
	"agent_retrieval_items": "Агент: найденных записей",
	"chat_retrieval_items": "Чат: найденных записей",
	"agent_recent_items": "Агент: недавних записей памяти",
	"memory_recent_items": "Память: недавних записей по умолчанию",
	"memory_retrieval_items": "Память: результатов поиска по умолчанию",
	"knowledge_chunk_chars": "Знания: символов в разделе",
	"knowledge_stream_batch_chars": "Знания: символов в пакете импорта",
	"knowledge_write_batch_items": "Знания: записей в пакете сохранения",
	"knowledge_search_items": "Знания: результатов поиска по умолчанию",
	"voice_tts_input_chars": "Windows Voice: символов TTS (после перезапуска)",
	"voice_cache_bytes": "Windows Voice: байтов кеша (после перезапуска)",
	"voice_mic_queue_chunks": "Windows Voice: блоков очереди микрофона (после перезапуска)",
	"voice_path_chars": "Windows Voice: символов пути (после перезапуска)",
	"voice_stft_n_fft": "Windows Voice DSP: размер FFT (после перезапуска)",
	"voice_stft_hop_length": "Windows Voice DSP: шаг FFT (после перезапуска)",

	"work_error_chars": "Work: символов ошибки",
	"work_summary_chars": "Work: символов итога",
	"work_action_chars": "Work: символов названия действия",
	"learning_seen_items": "Обучение: известных наблюдений",
	"learning_claim_items": "Обучение: утверждений с доказательствами",
	"learning_gap_items": "Обучение: открытых вопросов",
	"learning_audit_items": "Обучение: событий аудита",

	"agent_max_steps": "Агент: шагов задачи",
	"experience_failure_items": "Опыт: записей ошибок",
	"experience_checkpoint_items": "Опыт: контрольных точек",
	"experience_result_chars": "Опыт: символов результата",
	"code_input_chars": "Код: символов исходника",
	"code_repair_chars": "Код: символов исходника при ремонте теста",
	"code_rejected_chars": "Код: символов отвергнутого ответа",
	"code_files_chars": "Код: контекст файлов",
	"code_repair_files_chars": "Код: контекст файлов при ремонте",
	"code_consult_files_chars": "Код: контекст консультации",

	"chat_max_tokens": "Windows Core: токенов обычного ответа",
	"terse_max_tokens": "Windows Core: токенов короткого ответа",
	"memory_max_items": "Память: записей",
	"knowledge_max_items": "Прежнее Knowledge: записей",
	"dedupe_window": "Окно проверки дубликатов, записей",
	"index_batch": "Индексация: записей в пакете",
	"index_text_chars": "Индексация: символов записи",
	"vector_tokens": "Семантический индекс: токенов записи",
	"vector_features": "Семантический индекс: признаков записи",
	"task_trace_chars": "Память: символов следа задачи",
	"feedback_prompt_chars": "Feedback: символов запроса",
	"feedback_answer_chars": "Feedback: символов ответа",
	"feedback_summary_chars": "Feedback: символов итога",
	"feedback_observed_chars": "Feedback: символов наблюдения",
	"feedback_lesson_chars": "Feedback: символов урока",
	"direct_memory_chars": "Чат: символов найденной записи",
	"direct_history_items": "Чат: реплик истории",
	"direct_history_chars": "Чат: символов реплики",
	"agent_history_items": "Агент: реплик истории",
	"agent_history_chars": "Агент: символов реплики",
	"attachment_items": "Агент: вложений из реплики",
	"attachment_excerpt_chars": "Агент: символов фрагмента вложения",
	"attachment_metadata_chars": "Агент: символов метаданных",
	"context_message_chars": "Агент: символов собранной реплики",
	"tool_result_chars": "Агент: символов результата инструмента",
	"tool_result_items": "Агент: элементов результата инструмента",
}
static var _cached: Dictionary = {}
static var revision := 0

static func limits(path: String = PATH) -> Dictionary:
	var file := ConfigFile.new()
	file.load(path)
	var out := DEFAULTS.duplicate()
	for key in DEFAULTS:
		var candidate = file.get_value("resources", key, DEFAULTS[key])
		if _valid(key, candidate): out[key] = int(candidate)
	return out

static func value(key: String) -> int:
	if _cached.is_empty(): _cached = limits()
	return int(_cached.get(key, DEFAULTS.get(key, 0)))

static func minimum(key: String) -> int:
	if key == "voice_stft_n_fft": return 2
	if key == "voice_stft_hop_length": return 1
	return 1 if key in ["index_batch", "android_xls_file_bytes", "android_xls_directory_entries", "android_xls_directory_depth", "android_xls_shared_strings", "android_xls_sheets"] else 0

static func _valid(key: String, candidate: Variant) -> bool:
	if not (candidate is int or candidate is float): return false
	var number := float(candidate)
	if key in ["chat_max_tokens", "terse_max_tokens"] and number > 2147483647.0: return false
	if key in ["android_xls_directory_entries", "android_xls_directory_depth", "android_xls_shared_strings", "android_xls_sheets"] and number > 2147483647.0: return false
	if key == "voice_stft_n_fft" and number >= 2.0 and number == floor(number):
		var fft := int(number)
		return (fft & (fft - 1)) == 0
	# Representation only; no artificial maximum. A batch must make progress.
	return is_finite(number) and number >= minimum(key) and number < 9223372036854775807.0 and number == floor(number)

static func save(values: Dictionary, path: String = PATH) -> Error:
	var current := limits(path)
	for key in values:
		if not DEFAULTS.has(key) or not _valid(key, values[key]): return ERR_INVALID_PARAMETER
		current[key] = int(values[key])
	if int(current["voice_stft_hop_length"]) > int(current["voice_stft_n_fft"]) / 2:
		return ERR_INVALID_PARAMETER
	var file := ConfigFile.new()
	for key in current: file.set_value("resources", key, current[key])
	var err := file.save(path)
	if err == OK and path == PATH:
		_cached = current
		revision += 1
	return err

static func clip(text: String, key: String) -> String:
	var cap := value(key)
	return text if cap == 0 or text.length() <= cap else text.substr(0, cap)

static func count(size: int, key: String) -> int:
	var cap := value(key)
	return size if cap == 0 else mini(size, cap)
